// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { sqliteTable, AnySQLiteColumn, uniqueIndex, text, integer } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const esSystemAuthUser = sqliteTable("es_system__auth_user", {
	id: text().primaryKey().notNull(),
	name: text().notNull(),
	email: text().notNull(),
	emailVerified: integer("email_verified").default(0).notNull(),
	image: text(),
	createdAt: integer("created_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	updatedAt: integer("updated_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	isAnonymous: integer("is_anonymous").default(0),
	internalA: text("__internal_a"),
	banned: integer().default(0),
	banReason: text("ban_reason"),
	banExpires: integer("ban_expires"),
	lastLoginAt: integer("last_login_at"),
},
(table) => [
	uniqueIndex("es_system__auth_user_email_unique").on(table.email),
]);

export const bots = sqliteTable("bots", {
	id: text().primaryKey(),
	name: text().notNull(),
	type: text().notNull(),
	status: text().notNull(),
	uptime: text().notNull(),
	load: text().notNull(),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
});

export const files = sqliteTable("files", {
	id: text().primaryKey(),
	name: text().notNull(),
	type: text().notNull(),
	size: text().notNull(),
	date: text().notNull(),
	author: text().notNull(),
	content: text(),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
});

export const logs = sqliteTable("logs", {
	id: integer().primaryKey({ autoIncrement: true }),
	timestamp: text().notNull(),
	level: text().notNull(),
	message: text().notNull(),
});

export const profiles = sqliteTable("profiles", {
	userId: text("user_id").primaryKey(),
	subscriptionStatus: text("subscription_status").default("inactive"),
	subscriptionExpiry: integer("subscription_expiry"),
	walletAddress: text("wallet_address"),
	requirementsMet: text("requirements_met"),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
	updatedAt: integer("updated_at").default(sql`(unixepoch())`),
});

