-- ----------------------------------------------------------------
-- 🛑 DO NOT EDIT THIS FILE!
-- Regenerated by: edgespark pull schema --db
--
-- To modify your database schema (multiple statements in one command):
--   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
--     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
--     CREATE INDEX idx_posts_created ON posts(created_at)"
--
-- To query your database:
--   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
-- ----------------------------------------------------------------

-- TABLES

CREATE TABLE bots (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  status TEXT NOT NULL,
  uptime TEXT NOT NULL,
  load TEXT NOT NULL,
  created_at INTEGER DEFAULT (unixepoch())
);

CREATE TABLE `es_system__auth_user` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`email_verified` integer DEFAULT false NOT NULL,
	`image` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`is_anonymous` integer DEFAULT false,
	`__internal_a` text,
	`banned` integer DEFAULT false,
	`ban_reason` text,
	`ban_expires` integer,
	`last_login_at` integer
);

CREATE TABLE files (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  size TEXT NOT NULL,
  date TEXT NOT NULL,
  author TEXT NOT NULL,
  content TEXT,
  created_at INTEGER DEFAULT (unixepoch())
);

CREATE TABLE logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TEXT NOT NULL,
  level TEXT NOT NULL,
  message TEXT NOT NULL
);

CREATE TABLE messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  username TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at INTEGER DEFAULT (unixepoch())
);

CREATE TABLE profiles (
  user_id TEXT PRIMARY KEY,
  subscription_status TEXT DEFAULT 'inactive',
  subscription_expiry INTEGER,
  wallet_address TEXT,
  requirements_met TEXT,
  created_at INTEGER DEFAULT (unixepoch()),
  updated_at INTEGER DEFAULT (unixepoch())
, ai_id TEXT, telegram_id TEXT);

CREATE TABLE tasks (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  title TEXT NOT NULL,
  description TEXT,
  reward_amount TEXT,
  status TEXT DEFAULT 'pending',
  created_at INTEGER DEFAULT (unixepoch())
);

-- INDEXS

CREATE UNIQUE INDEX `es_system__auth_user_email_unique` ON `es_system__auth_user` (`email`);
